import { Command, CommandPriority } from "../types";

export const CommandNames: Record<Command, string> = {
  "000": "Poll",
  "001": "Status Report",
  "005": "Network Login",
  "500": "Command Acknowledge",
  "501": "Command Error",
  "502": "System Error",
  "505": "Login",
  "510": "Keypad LED State",
  "511": "Keypad LED Flash State",
  "601": "Zone Alarm",
  "602": "Zone Alarm Restore",
  "603": "Zone Tamper",
  "604": "Zone Tamper Restore",
  "605": "Zone Fault",
  "606": "Zone Fault Restore",
  "609": "Zone Open",
  "610": "Zone Restored",
  "615": "EnvisaLink Zone Timer Dump",
  "616": "Bypassed Zones Bitfield Dump",
  "620": "Duress Alarm",
  "621": "[F] Key Alarm",
  "622": "[F] Key Restore",
  "623": "[A] Key Alarm",
  "624": "[A] Key Restore",
  "625": "[P] Key Alarm",
  "626": "[P] Key Restore",
  "631": "2-Wire Smoke/Aux Alarm",
  "632": "2-Wire Smoke/Aux Restore",
  "650": "Partition Ready",
  "651": "Partition Not Ready",
  "652": "Partition Armed",
  "653": "Partition Ready - Force Arming Enabled",
  "654": "Partition In Alarm",
  "655": "Partition Disarmed",
  "656": "Exit Delay in Progress",
  "657": "Entry Delay in Progress",
  "658": "Keypad Lock-out",
  "659": "Partition Failed to Arm",
  "660": "PGM Output is in Progress",
  "663": "Chime Enabled",
  "664": "Chime Disabled",
  "670": "Invalid Access Code",
  "671": "Function Not Available",
  "672": "Failure to Arm",
  "673": "Partition is Busy",
  "674": "System Arming in Progress",
  "680": "System in Installers Mode",
  "700": "User Closing",
  "701": "Special Closing",
  "702": "Partial Closing",
  "750": "User Opening",
  "751": "Special Opening",
  "800": "Panel Battery Trouble",
  "801": "Panel Battery Trouble Restore",
  "802": "Panel AC Trouble",
  "803": "Panel AC Restore",
  "806": "System Bell Trouble",
  "807": "System Bell Trouble Restore",
  "814": "FTC Trouble",
  "815": "FTC Trouble Restore",
  "816": "Buffer Near Full",
  "829": "General System Tamper",
  "830": "General System Tamper Restore",
  "840": "Trouble LED On",
  "841": "Trouble LED Off",
  "842": "Fire Trouble Alarm",
  "843": "Fire Trouble Alarm Restore",
  "849": "Verbose Trouble Status",
  "900": "Code Required",
  "912": "Command Output Pressed",
  "921": "Master Code Required",
  "922": "Installers Code Required",
  S01: "Software Zone Alarm",
};

export const CommandPriorities: Partial<Record<Command, CommandPriority>> = {
  [Command.LOGIN]: CommandPriority.Medium,
  [Command.ZONE_ALARM_RESTORE]: CommandPriority.Medium,
  [Command.ZONE_TAMPER_RESTORE]: CommandPriority.Medium,
  [Command.ZONE_FAULT_RESTORE]: CommandPriority.Medium,
  [Command.ZONE_RESTORED]: CommandPriority.Medium,
  [Command.PARTITION_ARMED]: CommandPriority.Medium,
  [Command.PARTITION_DISARMED]: CommandPriority.Medium,
  [Command.EXIT_DELAY_IN_PROGRESS]: CommandPriority.Medium,
  [Command.ENTRY_DELAY_IN_PROGRESS]: CommandPriority.Medium,
  [Command.PARTITION_IS_BUSY]: CommandPriority.Medium,
  [Command.SYSTEM_ARMING_IN_PROGRESS]: CommandPriority.Medium,
  [Command.USER_CLOSING]: CommandPriority.Medium,
  [Command.SPECIAL_CLOSING]: CommandPriority.Medium,
  [Command.PARTIAL_CLOSING]: CommandPriority.Medium,
  [Command.USER_OPENING]: CommandPriority.Medium,
  [Command.SPECIAL_OPENING]: CommandPriority.Medium,
  [Command.PANEL_BATTERY_TROUBLE_RESTORE]: CommandPriority.Medium,
  [Command.PANEL_AC_RESTORE]: CommandPriority.Medium,
  [Command.SYSTEM_BELL_TROUBLE_RESTORE]: CommandPriority.Medium,
  [Command.GENERAL_SYSTEM_TAMPER_RESTORE]: CommandPriority.Medium,
  [Command.TROUBLE_LED_OFF]: CommandPriority.Medium,
  [Command.FIRE_TROUBLE_ALARM_RESTORE]: CommandPriority.Medium,

  [Command.PARTITION_IN_ALARM]: CommandPriority.High,
  [Command.KEYPAD_LOCK_OUT]: CommandPriority.High,
  [Command.PARTITION_FAILED_TO_ARM]: CommandPriority.High,
  [Command.INVALID_ACCESS_CODE]: CommandPriority.High,
  [Command.FUNCTION_NOT_AVAILABLE]: CommandPriority.High,
  [Command.FAILURE_TO_ARM]: CommandPriority.High,
  [Command.SYSTEM_IN_INSTALLERS_MODE]: CommandPriority.High,
  [Command.ZONE_ALARM]: CommandPriority.High,
  [Command.FIRE_TROUBLE_ALARM]: CommandPriority.High,
  [Command.CODE_REQUIRED]: CommandPriority.High,
  [Command.COMMAND_OUTPUT_PRESSED]: CommandPriority.High,
  [Command.MASTER_CODE_REQUIRED]: CommandPriority.High,
  [Command.INSTALLERS_CODE_REQUIRED]: CommandPriority.High,
  [Command.SOFTWARE_ZONE_ALARM]: CommandPriority.High,

  [Command.COMMAND_ERROR]: CommandPriority.Critical,
  [Command.SYSTEM_ERROR]: CommandPriority.Critical,
  [Command.ZONE_TAMPER]: CommandPriority.Critical,
  [Command.ZONE_FAULT]: CommandPriority.Critical,
  [Command.PANEL_BATTERY_TROUBLE]: CommandPriority.Critical,
  [Command.PANEL_AC_TROUBLE]: CommandPriority.Critical,
  [Command.SYSTEM_BELL_TROUBLE]: CommandPriority.Critical,
  [Command.FTC_TROUBLE]: CommandPriority.Critical,
  [Command.BUFFER_NEAR_FULL]: CommandPriority.Critical,
  [Command.GENERAL_SYSTEM_TAMPER]: CommandPriority.Critical,
  [Command.TROUBLE_LED_ON]: CommandPriority.Critical,
  [Command.VERBOSE_TROUBLE_STATUS]: CommandPriority.Critical,
};
